### ISSUE TITLE
Upgrade API/impl.

### ISSUE THREAD

**Issue by JohnKhandygo** [GolzitskyNikolay/ProgJava2k18#2]
- [x] Ни один из методов не обрабатывает случай `null` параметров. Явная обработка таких случаев в коде может быть и не обязательна, однако поведение программы в случае `null` параметров должно быть зафиксировано в Javadoc и тестах. То же самое касается и других краевых случаев, таких, например, как `name = ""` в методе `newContact` (понятно, что с точки зрения бизнес логики приложения добавление контакта с пустым именем не совсем корректно).
- [x] У Вас реализована несколько странная проверка формата входного номера в методе `newContact`. Я не понимаю, зачем там, например, `*` (по условию задачи, видимо, предполагается, что этот символ может участвовать в номерах типа `*100#`). Кроме того, он не допускает обычных городских номеров, добавочных номеров после `#` и кода страны, отличного от `+7` или `8`. Я бы посоветовал здесь убрать все ненужные символы, а затем провалидировать уже полученный номер.  В любом случае валидный формат должен быть зафиксирован в Javadoc, а проверка корректности валидации покрыта в тестах (как валидные, так и невалидные случаи). Таки образом, для удобства тестирования, валидацию входного номера стоит вынести в отдельный метод или класс. Для удобства написания тестов можно воспользоваться динамическими тестами в junit 5 (см., например, [здесь](https://howtoprogram.xyz/2016/08/21/junit-5-dynamic-tests/)).
- [x] По названию `newContact`  можно понять, что этот метод предназначен для создания новой записи в телефонной книге, однако Вы здесь также обрабатываете и добавление нового номера к существующему контакту. Необходимо либо изменить название метода, либо отразить поведение в Javadoc. В общем случае, конечно, Ваш код должен быть понятен и без Javadoc.
- [x] Ни один из методов не дает возможности программно определить, была ли операция успешна (например, был ли контакт успешно удален). Из-за этого, например, нельзя написать нормальный тест, который бы проверял поведение программы в случае добавления контакта с уже существующим номером. 
- [x] Метод `findPerson` может вернуть `null`, что не очень удобно для сторонних пользователей. В общем считается, что не стоит использовать `null` как значение, обозначающее отсутствие чего-либо. Вместо этого лучше использовать `Optional`.
- [x] Не понял, зачем Вы используете `Collections.sort(numbers)` в `findNumber`.

**Comment by JohnKhandygo** [comment]
Помимо неисправленных замечаний в предыдущем комментарии:

- [x] Вы нарушаете собственный стиль кодирования.
- [x] Не понятно, почему метод `numberIsCorrect` не проверяет конкретно формат номера, зато Вы делаете это отдельно.
- [x] `NullPointerException` предназначен для того, чтобы обозначать ошибки, связанные с обработкой `null` объектов. Я могу понять, если бы Вы бросали его в случае, когда имя или номер равны `null`, но если это пустые строки, это исключение здесь не к месту.
- [x] Раз уж у Вас нет проблем с тем, чтобы писать javadoc на английском, хотелось бы и сообщения к исключениям видеть также на английском. 
- [x] Метод `newContactOrAddNumber` в такой реализации может просто перетереть уже существующий контакт.

**Comment by GolzitskyNikolay** [comment]
Исправил

**Comment by GolzitskyNikolay** [comment]
Добавил динамический тест ко 2 замечанию. Сообщения к исключениям в javadoc описаны.
