### ISSUE TITLE
Задание 2.0

### ISSUE THREAD

**Issue by JohnKhandygo** [GolzitskyNikolay/ProgJava2k18#4]
**Общая формулировка**
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**cut**
Выделение из каждой строки текстового файла некоторой подстроки:
file задаёт имя входного файла. Если параметр отсутствует, следует считывать входные данные с консольного ввода;
Флаг -o ofile задаёт имя выходного файла (в данном случае ofile). Если параметр отсутствует, следует выводить результат на консольный вывод.
Флаг -с означает, что все числовые параметры задают отступы в символах (буквах) входного файла.
Флаг -w означает, что все числовые параметры задают отступы в словах (т.е. последовательностях символов без пробелов) входного файла.
Параметр range задаёт выходной диапазон и имеет один из следующих видов (здесь N и К -- целые числа):
-K диапазон от начала строки до K
N- диапазон от N до конца строки
N-K диапазон от N до K

Command line: cut [-c|-w] [-o ofile] [file] range

Программа построчно обрабатывает входные данные и для каждой строки выдаёт часть этой строки согласно заданному диапазону. Если какого-то из указанных файлов не существует или неправильно указаны параметры -c и -w (должен быть указан ровно один из них), следует выдать ошибку. Если в строке не хватает символов или слов, это ошибкой не является, в этом случае следует выдать ту часть входных данных, которая попадает в диапазон.

Кроме самой программы, следует написать автоматические тесты к ней.

P.S. Помимо этого необходимо написать инструкцию по сборке (получению .jar файла) Вашего проекта и скрипт (желательно bash, если Ваша система позволяет), который позволит вызывать написанную программу из командной строки (для проверки работы программы в реальных условиях). Если будете вести разработку в отдельном репозитории, сообщите в комментарии к этому issue.

**Comment by GolzitskyNikolay** [comment]
не работает argument

**Comment by JohnKhandygo** [comment]
Окей, что я обнаружил.
- В [примере](https://github.com/kohsuke/args4j/blob/master/args4j/examples/SampleMain.java) `@Argument` используется на списке. Вам это подходит. 
- В [javadoc](http://args4j.kohsuke.org/apidocs/org/kohsuke/args4j/Argument.html) сказано, что у `@Argument` есть параметр индекс, который фиксирует позицию аргумента. То есть Вы можете использовать его следующим образом:
  ```
  @Argument(index = 1)
  private String firstArgument

  @Argument(index = 2)
  private String secondArgument
  ```
  Если пойдете этим путем, то Вам придется поменять аргументы `range` и `file` местами. 

В любом случае Вам надо сначала разобраться, будет ли работать `@Argument` для входа типа `-4`. Если нет, то добавляем перед `file` ключ `-r` для указания интервала строк. В противном случае используйте любое подходящее решение, только напишите какое, чтобы я поправил описание задачи.

**Comment by JohnKhandygo** [comment]
Напишите, когда можно будет начинать проверку.

**Comment by GolzitskyNikolay** [comment]
Поменял range и file местами. Однако у параметра range не может быть входной тип "-число", поэтому я сделал его просто "число".  Можно так оставить или всё-таки добавить ключ?

**Comment by JohnKhandygo** [comment]
Лучше добавить ключ. Это вроде бы не должно вызывать больших проблем, а покрыть случай `-K` из условия как-то надо.

**Comment by GolzitskyNikolay** [comment]
Добавил ключ -r, теперь для использования range нужно писать его. Также немного обновил код с главным классом Cut и добавил тесты.
