### ISSUE TITLE
Upgrade 2.0

### ISSUE THREAD

**Issue by JohnKhandygo** [GolzitskyNikolay/ProgJava2k18#5]
В принципе код хорошо написан, но есть несколько нюансов: 
- [x] Кажется программа функционирует некорректно. Например, мне не понятно, почему в тестовом сценарии `cutWords` в выводе ожидается всего одна строка. По идее необходимо "обрезать" все остальные строки до нужного интервала. Например, от `язычковый кнопочно-пневматический музыкальный инструмент с` должны были остаться первые 5 слов. Ну и с остальными строками то же самое.  
- [x] В тестах не покрыты случаи ввода из консоли и интервала `-K`.
- [x] Я бы на Вашем месте в `Cut` оставил только самую основную логику, а считывание ввода и печать результата вынес бы отдельно. Мне кажется, что так будет удобнее тестировать приложение. Впрочем, как хотите.
- [x] Вообще в общей формулировке сказано: "При проектировании использовать объектно-ориентированный подход". У Вас же просто куча статических функций. 

Супер прицельно я код не смотрел, потому что программа функционирует некорректно. После исправления этих замечаний скорее всего будут еще уже просто по коду.

**Comment by GolzitskyNikolay** [comment]
Теперь программа работает корректно

**Comment by GolzitskyNikolay** [comment]
![image](https://user-images.githubusercontent.com/31801746/38570366-59ae9c7a-3cf6-11e8-9afb-79b32884966b.png)

**Comment by JohnKhandygo** [comment]
Списывание так-то карается. Штраф 0.5 баллов к этому заданию. 
- [x] Все еще не покрыты тестами ввод/вывод через консоль, а там ошибка.
- [x] Ошибка с записью в файл. Видимо, Вам все-таки придется вернуть тесты, которые проверяют запись в файл. 
- [x] По условию задания необходимо было разработать инструкцию по сборке/запуску Вашего приложения, я у Вас ее не вижу. Если бы Вы потрудились запустить свою программу в реальных условиях и нормально проверить ее работоспобность, было бы проще. 
- [x] Некоторые переменные определяете раньше времени. Если объявление перменной можно совместить с ее инициализацией, то стоит так и сделать. 
- [x] В `Cut::cutWords` и `Cut::cutSymbols` копипаст. Похожие блоки кода необходимо обобщать и выносить в отдельные функции/переменные. 
- [x] Метод `Cut::cutFromText` всегда возвращает список из одного элемента. А если подумать?
- [x] В ходе работы программы `range` регулярно проверяется на соответствие регулярному выражению (методы `Cut::checkAndConvertRange` и `Cut::cutFromText`), хотя очевидно никогда не меняется ([FYI](https://stackoverflow.com/questions/2469244/whats-the-difference-between-string-matches-and-matcher-matches)).
- [x] Мне кажется несколько странным то, что Вы используете `List` для хранения разобранного интервала. В конце концов, в интервале всегда не больше двух чисел. Для этих целей лучше завести самописный класс `Range` (в стандартной java библиотеке аналогов нет), хорошо подойдет любая стороння реализация интервала (например, [Range](https://github.com/google/guava/wiki/RangesExplained) из библиотеки [guava](https://github.com/google/guava)). 
- [x] Вообще у Вас много избыточного кода. Например, метод `Cut::listOfWords` можно сократить раза так в два. Вам необходимо привести код в более приемлемое состояние (отрефакторить).
- [x] В `CutLauncher` некорректно реализована проверка на присутствие хотя бы одного из флагов `-c` или `-v`. Стало быть и на это следует написать тесты. 
- [x] Нет проверки на то, что присутствует только один из флагов `-c` или `-v`. Понятно, что наличие обоих некорректно.
- [x] В тестах не покрыты случаи ввода/вывода на консоль. Учитывая, что вывод в файл у Вас работает, видимо, только из идеи, тестируйте полную связку.
- [x] Тестовый сценарий `outputFile` по факту ничего не проверяет. 
- [x] Файл `output/task2/OutputTestName` в проекте не нужен, поскольку является "побочным" продуктом выполнения тестов. Для junit5 к сожалению нет готового решения с tmp директориями, как это [было]((https://junit.org/junit4/javadoc/4.12/org/junit/rules/TemporaryFolder.html)) в junit4, поэтому достаточно просто удалять созданный файл. 
- [x] Файл `input/task2/for_task2` конечно же нужен для тестов, однако его принято складывать в папку с тестовыми ресурсами (resources). См. стандартный layout для maven проектов [здесь](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html). 

![qbgtfbs9dnu](https://user-images.githubusercontent.com/2545754/38575514-47c3b7a8-3d04-11e8-88e7-5f2c79587888.jpg)

**Comment by GolzitskyNikolay** [comment]
Довольно милый намёк) Но всё же... Не хочу показаться грубым, однако мне очень интересно когда, что и у кого я успел "списать"?! И почему вы так уверены в этом?

**Comment by JohnKhandygo** [comment]
У Вас pom.xml фактически идентичен pom'нику от Романа. Вы даже не потрудились проверить его работоспособность иначе заметили бы, что там неправильно указан main класс (вот же совпадение, он с классом Романа совпадает). Что ещё Вы списали, не знаю, да и не важно.

**Comment by GolzitskyNikolay** [comment]
Добавил скрипты cut.bat и cut.bash. Исправил большинство замечаний. Но остался вопрос c range: 

> В ходе работы программы range регулярно проверяется на соответствие регулярному выражению (методы Cut::checkAndConvertRange и Cut::cutFromText), хотя очевидно никогда не меняется

Если использовать Pattern.compile(regex) и Matcher, то тогда не понимаю как правильно обработать все 3 вида range и не зайти не в ту ветку.

**Comment by JohnKhandygo** [comment]
Все, что не отмечено галочками в предыдущих комментариях, актуально.
- [x] Исключение `NullPointerException` как правило используют для того, чтобы обозначить ошибку при работе с `null`. У Вас оно почему-то выбрасывается, когда неверная комбинация флагов используется. 
- [ ] Когда проектируется класс, предполагается, что он хранит какое-то состояние. В Вашем случае никакого состояния нет, Вы просто сделали все функции нестатическими.
- [x] В коде постоянно ковертируете списки строк в массивы и наоборот. А можно на чем-то одном остановиться?
- [x] Метод `cutFromText` возвращает экземпляр `StringBuilder`. Если после использования этой функции не предполагается дописывание строк к результату, то я не понимаю, почему не вернуть просто `String`.
- [x] Вместо `forEach(someList::add)` лучше использовать `collect(Collectors.toList())` (подробности см. [здесь](http://www.baeldung.com/java-8-collectors)).
- [x] Вызов `.split("")` выглядит по крайней мере странно. В конце концов есть `String::toCharArray` или `CharSequence::chars`, а при "обрезании" списка по интервалу совершенно не важно, что там внутри списка лежит. 
- [x] Неэффективно обрабатываются как ввод из консоли, так и ввод из файла: программа собирает все строки в список в памяти. Это значит, что при обработке больших файлов (длинных вводов из консоли), программа может упасть из-за нехватки выделенной ей памяти (то есть, например, для того, чтобы файл 2GB обработать, Вашей программе понадобится как минимум 2GB оперативной памяти отжать). 

> Если использовать Pattern.compile(regex) и Matcher, то тогда не понимаю как правильно обработать все 3 вида range и не зайти не в ту ветку.

Во-первых, можно завести три прекомпилированных регулярных выражения (статическими final переменными). Во-вторых, ссылку я кидал просто для ознакомления (fyi = for you information), а проблема заключается в том, что даже при подходе с `Pattern` программа все равно будет многократно парсить одно и то же выражение.

**Comment by GolzitskyNikolay** [comment]
1) > проблема заключается в том, что даже при подходе с Pattern программа все равно будет многократно парсить одно и то же выражение
А если вместо range.matches и Pattern сравнивать переменную regex с его 3 значениями, то это будет эффективнее? Можно так сделать?
![image](https://user-images.githubusercontent.com/31801746/39137506-6e6c042e-4726-11e8-9b1a-cdc42610ca54.png)
![image](https://user-images.githubusercontent.com/31801746/39137544-8a99f98a-4726-11e8-91f5-a40e53c2872f.png)

2) А какое тогда состояние мне использовать? Не совсем понимаю, что здесь имеется в виду.
> Когда проектируется класс, предполагается, что он хранит какое-то состояние. В Вашем случае никакого состояния нет, Вы просто сделали все функции нестатическими.

3)А его я уже давно удалил из проекта, разве нет?
> Файл output/task2/OutputTestName в проекте не нужен, поскольку является "побочным" продуктом выполнения тестов.

4)А как это можно сделать? Ошибки не вижу, файл создаётся в идее и в обычной cmd.
> Все еще не покрыты тестами ввод/вывод через консоль, а там ошибка.

> В тестах не покрыты случаи ввода/вывода на консоль. Учитывая, что вывод в файл у Вас работает, видимо, только из идеи, тестируйте полную связку.

**Comment by JohnKhandygo** [comment]
1. > А если вместо range.matches и Pattern сравнивать переменную regex с его 3 значениями, то это будет эффективнее? Можно так сделать?

    А какая собственно разница? Еще раз: Вы обрабатываете одну и ту же строку по несколько раз, хотя значения в ней не меняются. 

2. > А какое тогда состояние мне использовать? Не совсем понимаю, что здесь имеется в виду. 

    Тогда Вы не понимаете, что такое класс. Здесь очень сложно что-то посоветовать, фундаментально проблема достаточно сложная... Простейший (хоть и не совсем верный) способ приблизиться к пониманию ООП --- думать о классах как об абстракции над объектами в реальном мире. Далее стоит вспомнить о том, что в принципе ООП принято ассоциировать с некоторыми [свойствами](https://stackify.com/oops-concepts-in-java/) (на этом тоже нельзя заклициваться, думая о классах). Даже с этой точки зрения разработанный Вами класс ничего не моделирует и не обладает ни одним из представленных свойств. 

    В ООП есть два вида конструкций: интерфейсы и классы. Классы задают **состояние**, а интерфейсы **поведение** ([ссылка](https://stackoverflow.com/questions/18219339/trouble-understanding-object-state-behavior-and-identity)). Ваш класс не обладает ни состоянием, ни поведением. Если бы этот код был написан, на каком-нибудь C++, это был бы просто набор функций. Никаких классов для его выражения не понадобилось бы. Также стоит сказать, что, несмотря на то, что статические члены классов --- это неотъемлемая часть java, они зачастую считаются [плохой практикой](https://stackoverflow.com/questions/7026507/why-are-static-variables-considered-evil). 

3.  > А его я уже давно удалил из проекта, разве нет?

    У меня после прогона тестов в корне проекта создается файл OutputTestName. 

4. > А как это можно сделать? Ошибки не вижу, файл создаётся в идее и в обычной cmd.

    В последней версии вывод в файл, видимо, действительно работал, но суть комментария в отсутствии тестов на ввод/вывод из консоли. Тестировать ввод/вывод из консоли неприятно, но [можно](https://stackoverflow.com/questions/1119385/junit-test-for-system-out-println): `System.out` и `System.in` --- это просто потоки ввода/вывода (конйептуально примерно то же самое, что и поток записи в файл, например).

    Ошибка с выводом у Вас при вводе пустой строки. И в консоли, и в файле, по-меому. Поэтому покрывайте тестами оба случая.

**Comment by GolzitskyNikolay** [comment]
готово к проверке

**Comment by JohnKhandygo** [comment]
Вы, кажется, так и не уловили, что надо сделать с этим несчастным интервалом. Кроме того, у Вас в принципе по коду в некоторых местах есть проблемы. Приходите на пару в понедельник, обсудим.

**Comment by GolzitskyNikolay** [comment]
хорошо

**Comment by GolzitskyNikolay** [comment]
обновил код

**Comment by JohnKhandygo** [comment]
Окей, я готов закрыть это задание на 4, потому что замечание про ООП Вы так и не исправили.

**Comment by GolzitskyNikolay** [comment]
согласен

**Comment by JohnKhandygo** [comment]
Окей, закрыто на 4 - 0.5 (см. комментарий от 10 апреля).
