### ISSUE TITLE
Task 3.0

### ISSUE THREAD

**Issue by JohnKhandygo** [GolzitskyNikolay/ProgJava2k18#6]
Вам в принципе не очень много осталось исправить, поэтому можно задуматься над третьим заданием. Есть несколько вариантов. 
1. Получаете стандартное третье задание на написание графического приложения на Swing/JavaFX
2. Можете придумать свой вариант графического приложения, мы его обсудим и дополним/упростим по необходимости. По сложности должно получиться что-то типа многопользовательских шашек на одном компьютере.
3. Если Вам интересны какие-то конкретные направление в программировании (например, базы данных, web, Android), можно попробовать придумать задание с использованием этих технологий. 

Какой вариант Вам нравится больше всего?

**Comment by GolzitskyNikolay** [comment]
Вообще я почти написал сапёра. 
![image](https://user-images.githubusercontent.com/31801746/39616725-8a2d7c80-4f85-11e8-991d-b9ca663b01b1.png)

**Comment by JohnKhandygo** [comment]
Сапер годится.

**Comment by JohnKhandygo** [comment]
Пример из стадартного задания про сапера: 
> Обеспечить возможность настройки размера поля и количества мин. Реализовать все правила игры и проверить их работоспособность тестами.

От Вас ожидаю более менее формального описания поставленной задачи.

**Comment by GolzitskyNikolay** [comment]
В идеале я планирую:
--создать панель меню, в которой будут кнопки "Новая игра", "Настройки";
--сделать 3 карты разной размерности. Выбор карты будет осуществляться через кнопку "Настройки";
--реализовать все правила игры;
--установить регулировку сложности (по процентному числу бомб);
--при победе или проигрыше показывать диалоговое окно с выбором (выйти из игры или начать новую).

**Comment by JohnKhandygo** [comment]
Окей, годится.

**Comment by JohnKhandygo** [comment]
Второе задание зачтено, пишите, когда можно будет приступить к проверке третьего.

**Comment by GolzitskyNikolay** [comment]
можно сейчас

**Comment by GolzitskyNikolay** [comment]
В целом, сапёр работает, меню сделал, также добавил пару звуков

**Comment by JohnKhandygo** [comment]
Окей, если сегодня не получится, на неделе обязательно посмотрю.

**Comment by JohnKhandygo** [comment]
Во-первых, отсутствуют тесты. Во-вторых, Вам, наверное, будет сложно их писать, учитывая как сильно логика приложения завязана на графические компоненты. Мне кажется, что первым делом необходимо отвязать логику приложения от визуализации, но может быть Вы найдете какую-нибудь очень хорошую библиотеку для тестирования графики. Хотя даже в этом случае проверять Ваш код будет очень сложно. В таком состоянии, но с тестами я, пожалуй, готов зачесть это на 4. 

Кроме этого, есть несколько очень странных мест. Например, не могу понять, почему некоторые методы класса `RedrawCell` принимают аргументы принимают в качестве аргумента массив этих самых `RedrawCell`. Такое ощущение, что Вы очень плохо понимаете, как классы и их объекты работают. Или, например, метод `getNumberOfBombs`, который делает совсем не то, как он называется. 

В общем сначала тесты, потом буду дальше смотреть.

**Comment by GolzitskyNikolay** [comment]
Добавил тест, сравнивающий количество мин вокруг клетки с ожидаемым результатом. Собственно, не знаю что ещё тестировать в сапёре... 
И хотел спросить, с моим нынешним кодом какую оценку я могу получить за это задание?

**Comment by JohnKhandygo** [comment]
Код выглядит аккуратным, мне не нравится, что Вы так и не отвязали бизнес логику (то есть реализацию правил игры) от графики и я понятия не имею, как в таком случае Вы собираетесь показать, что Ваш код функционирует более менее корректно. Поэтому, без тестов, не больше тройки. 

> Собственно, не знаю что ещё тестировать в сапёре...

То же, что и в любом другом приложении: есть некие правила, по которым приложение должно функционировать, Вы пишите тесты, которые показывают на примере некоторых сценариев использования, что это действительно так. Тесты **не могут** доказать безусловную корректность функционирования кода, однако показывают, что в этих фиксированных (как правило, наиболее важных) сценариях использования все работает так, как должно. Мне кажется, что в случае сапера существует два основных компонента, подлежащих тестированию: генератор поля и собственно правила игры. Тестирование генератора поля не должно составить больших сложностей: надо просто аккуратно проверить, что во всяких краевых случаях все генерируется правильно, что, например, в клетке без бомбы не может стоять число больше шести. Тестирование правил игры производится по системе сценариев. Например, `если пользователь ткнул в кнопку с бомбой, то игра завершается`.

**Comment by JohnKhandygo** [comment]
Посмотрел код более внимательно: 
- Метод `RedrawCell::getNumberOfBombs` делает не то, как он назван.
- Методы `RedrawCell::showEmptyButtons`, `RedrawCell::changeButton` и `RedrawCell::makeFlag` **не должны** принимать массив всех кнопок поля с указанием индекса. Вспоминайте, как работают объекты классов.
- Все настройки игры хранятся статическими полями в классе `Field`. Мы же здесь ООП занимаемся, а не процедурным программированием. В java статические члены класса в принципе считаются [злом](https://stackoverflow.com/questions/7026507/why-are-static-variables-considered-evil).

**Comment by GolzitskyNikolay** [comment]
Вынес логику игры в отдельный класс GameLogic;
добавил в тесты вариант победы и поражения;
проверил, что каждая из кнопок имеет количество бомб меньшее 9;
избавился от злых статических членов класса.

**Comment by JohnKhandygo** [comment]
Зачтено на 4.5 за мелкие недочеты. Итого, за курсовой проект ставлю 4.

**Comment by GolzitskyNikolay** [comment]
хорошо, спасибо)
